### PR TITLE
Added Movies and Ability to create the playlist on per User basis

### PR DESCRIPTION
**Pull request by Whatchawnt**
1. Added new arguments.
2. Added Ability to select and apply the playlist for single/multiple/all Home Users to generate a tailored random playlist for (in order, based on their individual watched content).
3. Added the ability to select Shows from all Plex library sections.
4. Added the ability to select Movies from all Plex library sections.
5. Added the ability to mix and match movies and shows when generating playlist.
6. Added the ability to select specific library sections to choose shows/movies from.
7. Added the ability to exclude certain library sections from being added in the playlist generation process.
8. Added the ability to remove playlist from Home Users.
9. Changed the generation of the playlist for the admin user to be generated using the new argument —adminuser.

### CODE REVIEW

**Comment by ianweatherburn** [comment]
Line #1085
            if homeUser in plex_users:
fails with:
            NameError: name 'plex_users' is not defined. Did you mean: 'plex_user'?
            
for the following execution:

plex_playlist_generator.py \
  --name "TV Shows (Unwatched)" \
  --number 5 \
  --server --baseurl http://192.168.0.151:32400 --token [redacted] \
  --allshows \
  --exclude-library "Shows 4K" \
  --ignore-skipped \
  --homeusers "Hewey,Dewey,Louis,Donald"

**Comment by rich9474** [comment]
Thanks for adding to the functionality.

**Review by rich9474 — APPROVED** [review]

**Comment by Whatchawnt** [comment]
Oh, should be allHomeUsers, I’ll make a few changes to script and upload it.

**Comment by Whatchawnt** [comment]
I've updated it to fix the issues you pointed out, within a new pull request.

**Pull request merged**
